### ISSUE TITLE
Convertor error when try to get size of input

### ISSUE THREAD

**Issue by Toudsour** [microsoft/onnxruntime-extensions#101]
In the following code:

```python
import numpy as np
from onnxruntime_extensions.onnxprocess import torch_wrapper as torch
from onnxruntime_extensions.onnxprocess import trace_for_onnx, pyfunc_from_model, pyfunc_from_custom_op, build_customop_model


def authoring_custom_ops():
    inputs = ["sentence A", "sentence B", "sentence C"]

    with trace_for_onnx(inputs) as session:
        # get traced input from session
        inputs = session.get_inputs()
        input_size = inputs.size()[0]

authoring_custom_ops()
```
Fristly, the script will throw error `'list' object has no attribute 'size'`, this is because `get_inputs()` always return a list even when input is single.
 
After I fixed the list error by `inputs = session.get_inputs()[0]`, I got the following error:
```
/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_onnx_ops.py:71: UserWarning: The maximum opset needed by this model is only 8.
  warnings.warn('The maximum opset needed by this model is only %d.' % op_version)
Traceback (most recent call last):
  File "/home/toud/Code/scratch/Python/pytorch_convert/custom_convertor/demo.py", line 43, in <module>
    authoring_custom_ops()
  File "/home/toud/Code/scratch/Python/pytorch_convert/custom_convertor/demo.py", line 12, in authoring_custom_ops
    input_size = inputs.size()[0]
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_tensor.py", line 334, in size
    return self.create_and_verify(y, s[0])
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_tensor.py", line 297, in create_and_verify
    self.ort_verify(inputs, [ts_y])
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_tensor.py", line 286, in ort_verify
    result, model = cls.get_trace_session().runops(ts_from, ts_to)
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_session.py", line 252, in runops
    result = oxfunc(*[ts_.numpy() for ts_ in ts_from])
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/eager_op.py", line 96, in __call__
    self._ensure_ort_session()
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/eager_op.py", line 67, in _ensure_ort_session
    sess = _ort.InferenceSession(self.onnx_model.SerializeToString(), self.get_ort_session_options())
  File "/home/toud/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/toud/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 309, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:shape : Node (shape)'s input 0 is marked single but has an empty string in the graph

Process finished with exit code 1
``` 
The logic of creating ONNX graph is a bit complex, @wenbingl , can you look at where is wrong?

**Comment by wenbingl** [comment]
trace_for_onnx(inputs) usually needs the 'names' arguments.  Add the name generation if the names doesn't specified in this PR #104
