### ISSUE TITLE
Get error when input states of loop

### ISSUE THREAD

**Issue by Toudsour** [microsoft/onnxruntime-extensions#106]
It's still the last demo script, after fixing the error occurs when getting input size(), I get new error.

``` python
import numpy as np
from onnxruntime_extensions.onnxprocess import torch_wrapper as torch
from onnxruntime_extensions.onnxprocess import trace_for_onnx, pyfunc_from_model, pyfunc_from_custom_op, build_customop_model


def authoring_custom_ops():
    inputs = ["sentence A", "sentence B", "sentence C"]

    with trace_for_onnx(inputs) as session:
        # get traced input from session
        inputs = session.get_inputs()[0]
        input_size = inputs.size()[0]

        outputs = []

        # the following line is similar with the lambda in C++ :
        # [states...] (loop_count, condition) => {
        #     for (int i = 0; i < loop_count && condition; i++) {
        #        ...
        #     }
        # }
        # input_size : loop_count
        # True: condition
        ctr_flw = torch.control_flow()
        for states in ctr_flw.loop(input_size, True, inputs, outputs):
            # get index: i and states
            index, inputs, outputs = states
            gpt2_tokenizer = pyfunc_from_custom_op('GPT2Tokenizer', vocab_file="...", merges="...", max_length=100)
            outputs.append(gpt2_tokenizer(inputs[index]))

            ctr_flw.flow_output(outputs)

        outputs = ctr_flw.finalize()

        nn_model = pyfunc_from_model("core_model.onnx")

        result = nn_model(outputs)

        session.save_as_onnx("./e2e_model.onnx", result)
        return result


authoring_custom_ops()
``` 
I get error when I try to input states of loop:

```
/usr/bin/python3.8 /home/toud/Code/scratch/Python/pytorch_convert/custom_convertor/demo.py
/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_session.py:223: UserWarning: the name number doesn't match the inputs', assign to the ones in the front.
  warnings.warn("the name number doesn't match the inputs', assign to the ones in the front.")
/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_onnx_ops.py:71: UserWarning: The maximum opset needed by this model is only 8.
  warnings.warn('The maximum opset needed by this model is only %d.' % op_version)
Traceback (most recent call last):
  File "/home/toud/Code/scratch/Python/pytorch_convert/custom_convertor/demo.py", line 43, in <module>
    authoring_custom_ops()
  File "/home/toud/Code/scratch/Python/pytorch_convert/custom_convertor/demo.py", line 25, in authoring_custom_ops
    for states in ctr_flw.loop(input_size, True, inputs, outputs):
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_tensor.py", line 581, in loop
    self.loop_states = [_EagerTensor(st_.value, st_.name) for st_ in states]
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_tensor.py", line 581, in <listcomp>
    self.loop_states = [_EagerTensor(st_.value, st_.name) for st_ in states]
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_tensor.py", line 264, in __getattribute__
    return object.__getattribute__(self, attr)
  File "/home/toud/Code/ort-customops/onnxruntime_extensions/onnxprocess/_tensor.py", line 34, in value
    return self.raw_data if self.raw_data else self._t
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
It's because input itself has already been a EagerTensor or it is still a list... What expected is a torch tensor...
```python
        self.loop_states = [_EagerTensor(st_.value, st_.name) for st_ in states]
```
I think we should provide a common function to convert EagerTensor/TorchTensor/Numpy/List/BasisElement to EagerTensor.

**Comment by wenbingl** [comment]
@Toudsour using the torch api to get an EagerTensor.

instead of 'True', it should be torch.tensor(True)
