### ISSUE TITLE
MSAN complains of use-of-uninitialized-value on inference output tensor

### ISSUE THREAD

**Issue by ns-wxin** [microsoft/onnxruntime-extensions#360]
During our Memory Sanitizer Test, the MSAN complained output tensor from onnxruntime extension usage of inference. I want to emphasize that even though MSAN claims it's un-initialized, we're still able to retrieve the expected values from the output tensor. We have similar code that uses non-extension code which doesn't get such MSAN complaint. The only difference is this code has "m_sessionOptions.EnableOrtCustomOps()".

This is Ubuntu 16.04 and Onnxruntime 1.12.1 built with extensions. 

    Uninitialized value was stored to memory at
        #0 0x46631a in __msan_memcpy.part.0 /root/toolchain_build/llvm-project-15.0.3.src/compiler-rt/lib/msan/msan_interceptors.cpp:1606:3
        #1 0x7feeb6208150 in onnxruntime::Reshape::Compute(onnxruntime::OpKernelContext*) const (/opt/3p/lib/libonnxruntime.so.1.12.1+0x14a8150)
  
    Uninitialized value was stored to memory at
        #0 0x7feeb5642096 in void Eigen::internal::call_dense_assignment_loop<Eigen::Map<Eigen::Matrix<float, -1, 1, 0, -1, 1>, 0, 
     Eigen::Stride<0, 0>>, Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float, float>, 
     Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<float, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0>>> const, 
     Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Array<float, -1, 1, 0, -1, 1> const> const>, 
     Eigen::internal::assign_op<float, float>>(Eigen::Map<Eigen::Matrix<float, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0>>&, 
     Eigen::CwiseBinaryOp<Eigen::internal::scalar_quotient_op<float, float>, 
     Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<float, -1, 1, 0, -1, 1> const, 0, Eigen::Stride<0, 0>>> const, 
     Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::Array<float, -1, 1, 0, -1, 1> const> const> const&, 
     Eigen::internal::assign_op<float, float> const&) (/opt/3p/lib/libonnxruntime.so.1.12.1+0x8e2096)
  
    Uninitialized value was created by a heap allocation
        #0 0x474d30 in posix_memalign /root/toolchain_build/llvm-project-15.0.3.src/compiler- 
     rt/lib/msan/msan_interceptors.cpp:160:3
       #1 0x7feeb6927c48 in onnxruntime::CPUAllocator::Alloc(unsigned long) (/opt/3p/lib/libonnxruntime.so.1.12.1+0x1bc7c48)

Our source code looks like the following:

    std::vector<float> outputTensorValues(OutputTensorSize, 0.0);
    DLOG(3) << "dumping outputTensor";
    // __msan_print_shadow(&outputTensorValues[0], sizeof(float) * outputTensorValues.size());
    __msan_print_shadow(outputTensorValues.data(), sizeof(float) * outputTensorValues.size());

    std::vector<Ort::Value> inputTensors;
    std::vector<Ort::Value> outputTensors;
    std::vector<const char *> inputNames{m_inputName};
    std::vector<const char *> outputNames{m_outputName};
    t2_start = std::chrono::high_resolution_clock::now();

    Ort::Value text_tensor = Ort::Value::CreateTensor(m_allocator,
                                                      m_inputDims.data(),
                                                      m_inputDims.size(),
                                                      ONNX_TENSOR_ELEMENT_DATA_TYPE_STRING);
    text_tensor.FillStringTensor(&inputText, 1U);

    inputTensors.push_back(std::move(text_tensor));

    // outputTensors.emplace_back(Ort::Value::CreateTensor<float>(m_memoryInfo,
    outputTensors.emplace_back(Ort::Value::CreateTensor<float>(m_memoryInfo,
                                                               outputTensorValues.data(),
                                                               OutputTensorSize,
                                                               m_outputDims.data(),
                                                               m_outputDims.size()));

    m_modelSession.Run(Ort::RunOptions{nullptr},
                       inputNames.data(),
                       inputTensors.data(),
                       1,
                       outputNames.data(),
                       outputTensors.data(),
                       1);

    t_end = std::chrono::high_resolution_clock::now();
    auto duration =
        std::chrono::duration_cast<std::chrono::milliseconds>(t_end - t2_start).count();
    LOG(INFO) << "Onnx took " << duration << " millisecs.";

    DLOG(3) << "dumping outputTensor, again: ";
    // __msan_print_shadow(&outputTensorValues[0], sizeof(float) * outputTensorValues.size());
    __msan_print_shadow(outputTensorValues.data(), sizeof(float) * outputTensorValues.size());
    DLOG(3) << "first 3 values: " << outputTensorValues.data()[0] << ", " << outputTensorValues.data()[1] << ", " << outputTensorValues.data()[2];
    __msan_print_shadow(&outputTensorValues[0], sizeof(float)) ;
    __msan_print_shadow(&outputTensorValues[1], sizeof(float));
    __msan_print_shadow(&outputTensorValues[2], sizeof(float));
    return outputTensorValues;

As you can see when I first created "outputTensors", it was initialized. Then after I call Run() and returned output tensor changed and the MSAN print_shadow shows the output tensor was un-initialized:

    023-02-11 20:23:08     DEBUG   localhost       5090         DLPFP 0:TextMLFingerprintGenerator.cpp:00117 trid=0 rqid=0 
    tenantid=0 user='' dumping outputTensor
    Shadow map [0x20d000004100, 0x20d0000041c8) of [0x70d000004100, 0x70d0000041c8), 200 bytes:
    0x20d000004100[0x70d000004100]: 00000000 00000000 00000000 00000000
    0x20d000004110[0x70d000004110]: 00000000 00000000 00000000 00000000
    0x20d000004120[0x70d000004120]: 00000000 00000000 00000000 00000000
    0x20d000004130[0x70d000004130]: 00000000 00000000 00000000 00000000
    0x20d000004140[0x70d000004140]: 00000000 00000000 00000000 00000000
    0x20d000004150[0x70d000004150]: 00000000 00000000 00000000 00000000
    0x20d000004160[0x70d000004160]: 00000000 00000000 00000000 00000000
    0x20d000004170[0x70d000004170]: 00000000 00000000 00000000 00000000
    0x20d000004180[0x70d000004180]: 00000000 00000000 00000000 00000000
    0x20d000004190[0x70d000004190]: 00000000 00000000 00000000 00000000
    0x20d0000041a0[0x70d0000041a0]: 00000000 00000000 00000000 00000000
    0x20d0000041b0[0x70d0000041b0]: 00000000 00000000 00000000 00000000
    0x20d0000041c0[0x70d0000041c0]: 00000000 00000000 ........ ........

    2023-02-11 20:23:08      INFO   localhost       5090         DLPFP 0:TextMLFingerprintGenerator.cpp:00153 trid=0 rqid=0 
    tenantid=0 user='' Onnx took 1 millisecs.
    2023-02-11 20:23:08     DEBUG   localhost       5090         DLPFP 0:TextMLFingerprintGenerator.cpp:00155 trid=0 rqid=0 
    tenantid=0 user='' dumping outputTensor, again:
    Shadow map [0x20d000004100, 0x20d0000041c8) of [0x70d000004100, 0x70d0000041c8), 200 bytes:
    0x20d000004100[0x70d000004100]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004110[0x70d000004110]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004120[0x70d000004120]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004130[0x70d000004130]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004140[0x70d000004140]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004150[0x70d000004150]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004160[0x70d000004160]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004170[0x70d000004170]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004180[0x70d000004180]: ffffffff ffffffff ffffffff ffffffff
    0x20d000004190[0x70d000004190]: ffffffff ffffffff ffffffff ffffffff
    0x20d0000041a0[0x70d0000041a0]: ffffffff ffffffff ffffffff ffffffff
    0x20d0000041b0[0x70d0000041b0]: ffffffff ffffffff ffffffff ffffffff
    0x20d0000041c0[0x70d0000041c0]: ffffffff ffffffff ........ ........

    2023-02-11 20:23:08     DEBUG   localhost       5090         DLPFP 0:TextMLFingerprintGenerator.cpp:00158 trid=0 rqid=0 
    tenantid=0 user='' first 3 values: 2.20749, -1.0468, -0.760595
    Shadow map [0x20d000004100, 0x20d000004104) of [0x70d000004100, 0x70d000004104), 4 bytes:
    0x20d000004100[0x70d000004100]: ffffffff ........ ........ ........

    Shadow map [0x20d000004104, 0x20d000004108) of [0x70d000004104, 0x70d000004108), 4 bytes:
    0x20d000004104[0x70d000004104]: ffffffff ........ ........ ........

    Shadow map [0x20d000004108, 0x20d00000410c) of [0x70d000004108, 0x70d00000410c), 4 bytes:
    0x20d000004108[0x70d000004108]: ffffffff ........ ........ ........

**Comment by wenbingl** [comment]
from the stack, it looks like there is something wrong in Eigen library.
Can you share what's the operator are used in onnx model, or share a dummy model that can repro this issue?

**Comment by ns-wxin** [comment]
this should be the model I'm using:
https://tfhub.dev/google/tf2-preview/nnlm-en-dim50/1
