### ISSUE TITLE
Onnxruntime JAR for darwin aarch64

### ISSUE THREAD

**Issue by github-gauthier-perrod** [microsoft/onnxruntime-extensions#736]
Hello, first of all thank you for publishing on maven ORT Extensions on maven.

I have an issue using in on m1/m2 macbook :

`[info] Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File /ai/onnxruntime/extensions/native/osx-aarch64/libonnxruntime_extensions4j_jni.dylib was not found inside JAR.
[info] 	at ai.onnxruntime.extensions.OrtxLibrary.<clinit>(OrtxLibrary.java:104)
[info] 	... 20 more
[info] Caused by: java.io.FileNotFoundException: File /ai/onnxruntime/extensions/native/osx-aarch64/libonnxruntime_extensions4j_jni.dylib was not found inside JAR.
[info] 	at ai.onnxruntime.extensions.OrtxLibrary.<clinit>(OrtxLibrary.java:86)
[info] 	... 20 more `

**Comment by wenbingl** [comment]
@sayanshaw24

**Comment by github-gauthier-perrod** [comment]
Hello, i came to realize we have the same issue for arch64 architecture on ubuntu:

`java.lang.RuntimeException: java.io.FileNotFoundException: File /ai/onnxruntime/extensions/native/linux-aarch64/libonnxruntime_extensions4j_jni.so was not found inside JAR.`

**Comment by Craigacp** [comment]
The published jar is still missing native platform support for macos arm64 and Linux arm64 which is present in ORT.

**Comment by Craigacp** [comment]
This is still a problem, and the latest release still hasn't been published to Maven Central.
