### ISSUE TITLE
com.microsoft.onnxruntime:onnxruntime-extensions:0.11.0: missing RegisterCustomOps in onnxruntime_extensions4j_jni.dll

### ISSUE THREAD

**Issue by david-sitsky** [microsoft/onnxruntime-extensions#764]
I am using OnnxRuntime extensions 0.11.0 in Java via DJL, and while this all works fine on Linux, the same code on Windows fails during initialisation on the `OrtSession.SessionOptions.registerCustomOpLibrary()` call:
```
Caused by: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Failed to find symbol RegisterCustomOps in library, error code: 127 ""
	at ai.onnxruntime.OrtSession$SessionOptions.registerCustomOpLibrary(Native Method) ~[onnxruntime-1.17.3.jar:1.17.3]
	at ai.onnxruntime.OrtSession$SessionOptions.registerCustomOpLibrary(OrtSession.java:868) ~[onnxruntime-1.17.3.jar:1.17.3]
```
I have noticed the size of the embedded native libraries within com.microsoft.onnxruntime:onnxruntime-extensions:0.11.0 seems vastly different between Windows and Linux:
```
$ ls -lh
total 193M
-rw-rw-r-- 1 sits sits 8.8M May 24 23:32 libonnxruntime_extensions4j_jni.dylib
-rw-rw-r-- 1 sits sits 176M May 24 23:33 libonnxruntime_extensions4j_jni.so
-rw-rw-r-- 1 sits sits 8.1M May 24 23:33 onnxruntime_extensions4j_jni.dll
```
The Linux shared object file is almost 10x the size of the Windows (and macOS) libraries.  Is something missing leading to this issue?
I can see the .so file does have the symbol mentioned:
```
$ nm -gD libonnxruntime_extensions4j_jni.so | grep RegisterCustomOps
0000000000152bc0 T RegisterCustomOps
```
I opened the .dll with Ghidra and RegisterCustomOps seems to be missing.

Is there a build problem here, or have I missed something?

**Comment by david-sitsky** [comment]
As a point of comparison, from https://globalcdn.nuget.org/packages/microsoft.ml.onnxruntime.extensions.0.10.0.nupkg package, the linux-x86 .so file is only 5.1MB and the win-x64 ortextensions.dll file is 6.9MB.  

So surely libonnxruntime_extensions4j_jni.so being 176MB for Linux is packaging up too much?

Anybody have any ideas what is going on here?  I am hoping to use extensions in my project for both Windows and Linux, but this is currently a blocker.

**Comment by david-sitsky** [comment]
I can also see ortextensions.dll from the nupkg file does indeed export `RegisterCustomOps`, but onnxruntime_extensions4j_jni.dll does not.

**Comment by wenbingl** [comment]
@sayanshaw24 , can you follow up with these issues that @david-sitsky mentioned here?

**Comment by Binozo** [comment]
This issue also exists for CocoaPods/iOS.

I am importing the newest version of onnxruntime extensions using
`s.dependency 'onnxruntime-extensions-c', '0.13.0'` but the published package is completely missing the `RegisterCustomOps` symbol

**Comment by Binozo** [comment]
What makes this problem even worse is the fact that in iOS it's almost impossible to import local packages because the CocoaPods team is driving an anti-developer ideology and actively refusing to even allow such a feature since almost 10 years.

For Android and Windows/Linux I built the runtime and extensions library myself and imported it with no problems

**Comment by david-sitsky** [comment]
Are we really not going to fix this?  It basically makes using ONNX extensions a non-starter with Java via Maven/Gradle until this fixed.  As a workaround, I just extracted the native libraries I needed manually, but we shouldn't inflict this pain on future developers.

**Comment by Craigacp** [comment]
The Linux binary is a normal size and the Windows dll seems to export the RegisterCustomOps symbol now, so this seems to be fixed for Java. I don't know anything about how iOS packages things though so I don't know if that is fixed.

**Comment by david-sitsky** [comment]
Excellent!  Maybe we should properly mark this as fixed then rather than stale.
